.circleci/config.yml
src/commands/install-firefox.yml

we upgrade to `edge` on alpine in order to get the latest version of the firefox apk, which involves updating the `/etc/apk/repositories` file, & our current regex only matches `[0-9].[0-9]` (e.g., fails if there are 2-digit numbers, & fails if there is a second set of `.n` (never the case currently, but alpine could decide to do so)
- fix regex to capture any semantic version string
- also, use `perl` instead of `sed`

fix apk repositories regex

---

.circleci/config.yml
src/commands/install-firefox.yml

https://github.com/CircleCI-Public/browser-tools-orb/issues/7
- modify version-check `grep` logic to account for possibility of `esr` string
- also add some missing libraries and shasum-checking for older FF releases (issues were unearthed in testing the orb with various older ESR releases)
- branch is failing due to an unrelated geckodriver issue in a single Alpine job ([which has been separately reported here](https://github.com/CircleCI-Public/browser-tools-orb/issues/9)); however, all `install-firefox` commands are completing successfully

[CIRCLE-23379] patch `install-firefox` to support ESR releases across all execution envs

---

src/commands/install-chrome.yml

Current `install-chrome` command failing with error `/bin/bash: line 97: sudo: command not found`.
Remove hardcoded reference to `sudo`, instead using the $SUDO used elsewhere in the script (allowing for configurable use of sudo).

[semver:patch] Remove hardcoded `sudo` reference

---

src/commands/install-chrome.yml

cask was removed from brew as of 2.6.0
https://brew.sh/2020/12/01/homebrew-2.6.0/
just remove `cask` from the `brew install` commands

rm cask from chrome install on mac [semver:patch]

---

src/commands/install-chromedriver.yml

The script to extract the version of Chrome is broken, meaning that Chromedriver installation fails.
When I run `google-chrome --version` on a CircleCI instance I get something like this:
circleci@a1afdd3e551e:~$ google-chrome --version
v12.20.2 is already installed.
Now using node v12.20.2 (npm v6.14.11)
Now using node v12.20.2 (npm v6.14.11)
Google Chrome 88.0.4324.182 
This is a multi-line response, with lots of text about node and npm.  Running the script lines for Chromedriver manually, we get:
circleci@a1afdd3e551e:~$ CHROME_VERSION="$(google-chrome --version)"
v12.20.2 is already installed.
circleci@a1afdd3e551e:~$ echo $CHROME_VERSION | sed 's/^Google Chrome //' | sed 's/^Chromium //' 
Now using node v12.20.2 (npm v6.14.11) Now using node v12.20.2 (npm v6.14.11) Google Chrome …

[semver:patch] Fix misparsing version from `google-chrome --version`

---

src/commands/install-chrome.yml

~~- [ ] All new jobs, commands, executors, parameters have descriptions~~
~~- [ ] Examples have been added for any significant new features~~
~~- [ ] README has been updated, if necessary~~
I'm getting this error on our circleci builds with browser-tools orbs version 1.1.1 and above.
```
Google Chrome is not currently installed; installing it
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Reading package lists... Done      
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this …
```

Allow updates when release info changes

---

.circleci/config.yml
src/commands/install-chrome.yml

Closes #31 
This fixes an issue where sometimes the dependencies for Google Chrome don't get installed. This happens when the Apt index isn't available.
Also updated to Orb Tools v10 here and added addition tests to catch an issue like this in the future.

Fix Chrome dep issue not always installing [semver:patch]

---

src/commands/install-chrome.yml

Fixes #33. This tries to improve the current process.
In Issue #40, we might try a completely different way to install Chrome. Especially if the install still proves to be flaky after this PR is published.

Improve Chrome download chance [semver:patch]

---

src/scripts/install-chrome.sh

I checked an older version of the orb. `google-chrome` was always a Bash script for macOS. So I copied that method instead of using an alias or symlink.

Use a bash script like the old method

---

.circleci/config.yml
.circleci/test-deploy.yml
src/scripts/install-chrome.sh

- MacOS now downloads the Chrome package from Google directly rather than relying on HomeBrew.
- Time to install with HomeBrew: _~10 - ~13_ _**minutes**_
- Time to install with PKG: **_Under 30 seconds_**
- Solves:
- #44 
- #43 
- #49 
- Linux now downloads Chrome via the official Google APT repository
- Linux users have been reporting a higher % chance of the download failing when pulling from Google directly. We believe this _may_ be due to some form of rate limiting on Google's end.
- We hope by moving to the official APT repo we may not experience the same limitations if any are present.
- Enabled GitHub PR commenting from Orb Tools 11, was not enabled in the previous PR

feat: Resolve Chrome download issues in MacOS and Linux

---

.circleci/config.yml
.circleci/test-deploy.yml
src/scripts/install-chrome.sh
src/scripts/install-chromedriver.sh

fixes #62 
This PR does a few things:
1. The main purpose of this PR is to fix an issue caused upstream with Chromedriver. A new release started to create a file in the filestem when run. This file `~/project/LICENSE.chromedriver`, created when we run `chromeversion --version`, caused a problem with CircleCI's checkout step. This file is now deleted via the orb.
2. We moved around the chromedriver step in order to add an additional test to help catch this issue in the future.
3. The new test caught another issue happening with the beta Google Chrome on macOS. This was fixed as well.
4. We're using the new context targeted to orbs owned by the Images subteam.

fix: correct checkout directory error

---

src/scripts/install-chrome.sh

Chrome installations on ARM executors fails due to a bad architecture check causing it to use amd64 instead of arm64
Fixed ENV_IS_ARM variable

fix(install-chrome.sh): Chrome install not working on ARM executors

---

src/examples/install_browsers.yml
src/examples/install_chrome.yml

Documentation includes an invalid version of node with no clear reference to how to correct it.
Using the examples as is in the `main` branch produces the following error if used in your app's configuration:
```
Error response from daemon: manifest for cimg/node:13.12-browsers not found: manifest unknown: manifest unknown
```
This updates the examples to a valid node version based on the latest in the list at https://circleci.com/developer/images/image/cimg/node

Update example documentation with a valid node version

---

src/scripts/install-chromedriver.sh

Adds an `else` statement to the `determine chromedriver release` conditional to prevent accidental halts in the `installation check` step in `install-chromedriver.sh` as mentioned in issue #79. This should close #79 and be the final patch release cut for version 1.4 in the near future.

fix: installation check failures

---

src/scripts/install-chromedriver.sh

This fixes the new issue arisen in #95 with chromedriver installs now failing again. This issue was caused by the timestamp output of [this endpoint]([this endpoint](https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone.json)) containing a string that matched the major version of stable. 
Output: 
```{"timestamp":"2023-09-12T18:09:06.116Z","milestones":{"113":{"milestone":"113","version":"113.0.5672.63","revision":"1121455"},"114":{"milestone":"114","version":"114.0.5735.133","revision":"1135570"},"115":{"milestone":"115","version":"115.0.5790.170","revision":"1148114"},"116":{"milestone":"116","version":"116.0.5845.96","revision":"1160321"},"117":{"milestone":"117","version":"117.0.5938.62","revision":"1181205"},"118":{"milestone":"118","version":"118.0.5993. …
```

fix: chromedriver versions not installing

---

src/scripts/install-chromedriver.sh

This is a possible solution to https://github.com/CircleCI-Public/browser-tools-orb/issues/104.
A possibly better solution would be to update the script to not infer the URL but rather read from https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone-with-downloads.json to get the download link directly.  I probably recommend that over this solution, so if someone wants to tackle, go for it.
The chrome-for-testing release moved newer versions of chromedriver >= 121 to a new CDN (leaving older versions in place).  See this commit: https://github.com/GoogleChromeLabs/chrome-for-testing/commit/3bfd77e1ea8df7b38651780351ab619f52d19aa2
Hard to say for sure if this was completely intended but assuming this is their plan moving forward for storage of release versions, …

fix: dynamic CDN URL based on chrome-for-testing version

---

.circleci/test-deploy.yml
src/scripts/install-chrome.sh
src/scripts/install-chromedriver.sh
src/scripts/install-geckodriver.sh

Fix script for installing specific Chrome version with APT
- [N/A] All new jobs, commands, executors, parameters have descriptions
- [N/A] Examples have been added for any significant new features
- [N/A] README has been updated, if necessary
When installing a specific version of Chrome on a Debian-based distro, the APT repositories were not refreshed by running `apt-get update` beforehand, leading to the install process failing due to unresolvable dependencies:
```bash
Google Chrome is not currently installed; installing it
Preparing Chrome installation for Debian-based systems
2023-08-30 11:21:36 URL:https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.96-1_amd64.deb [96765132/96765132] -> "/tmp/chrome.deb" [1]
Reading package lists... …
```

Fix script for installing specific Chrome version with APT

---

.circleci/test-deploy.yml
src/scripts/install-chrome.sh

Resolves #57 
Update the conditions to remove an existing installation, so it only happens if the version installed is different to the required version.

Update replace existing chrome validation

---

src/scripts/install-chrome.sh

When trying to download a specific version of chrome beta, the orb errors that the version cannot be found.
```yml
- browser-tools/install-chrome:
channel: beta
chrome-version: 134.0.6998.3
```
results in this output:
Based on the output, it looks like the version is being sourced from the wrong channel. https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-beta/google-chrome-beta_134.0.6998.3-1_amd64.deb is a valid download URL.
This PR adds the channel into the download url over the hardcoded stable to be able to flex on the channel passed in over always using `stable`.

fix: allow for specific chrome beta version download and not just latest

---

src/scripts/install-chrome.sh
src/scripts/install-chromedriver.sh

There is bad logic when install chrome on `arm64` instances. 
```bash
ENV_IS_ARM=$(! dpkg --print-architecture | grep -q arm; echo $?)
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | $SUDO apt-key add -
if [ "$ENV_IS_ARM" == "arm" ]; then
echo "Installing Chrome for ARM64"
```
`ENV_IS_ARM` will always be `1` if the arch is `arm64` and `0` when the arch is does not contain the word `arm`. This fails the if statement as its looking for a string `arm`. 
This results in `arm64` systems falling into the if/else block below which is for `AMD64`. 
Since `chrome` and `chrome-driver` do not officially support `arm64` on Linux, I changed the logic to echo the error and then exit. 
Long term, it would be nice to offer alternatives for folks who need to test there applications on …

Fix/Remove Arm64 Support for Chrome and Chrome Driver

---

.circleci/config.yml
.circleci/test-deploy.yml
src/commands/install-firefox.yml
src/scripts/install-firefox.sh

Decided to avoid caching firefox version when the version set is latest.
Having the _latest_ version cached causes more issues than it solves. As the version is constantly moving, a cache invalidation is common, which removes the purpose of cache. Also, there is not a good way to know which version is required when this changes happen, if the cached or the actual latest.
This change should resolve #120

Use cache for firefox only when version is not latest

---

src/scripts/install_chrome_for_testing.sh

Closes #140
Looks like there is an issue where Chrome for Testing is not linked properly after install. This PR moves the unzipped package to the `/opt` directory for linux and mac and symlinks the binary to `/usr/local/bin/chrome`
I also removed the `$SUDO apt-get satisfy -y --no-install-recommends "${pkg}";` as it tends to hang when there are no updates available. I could not get this part of the script to run

fix: make sure chrome for testing is installed and linked properly
